# Generated by Django 3.0.6 on 2020-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasosPorCidadePiaui',
            fields=[
                ('idIBGE', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='IBGE ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('casos', models.IntegerField(verbose_name='Casos')),
                ('obitos', models.IntegerField(verbose_name='Óbitos')),
            ],
            options={
                'verbose_name': 'CasosPorCidadePiaui',
                'verbose_name_plural': 'CasosPorCidadePiauis',
            },
        ),
    ]
